name: jentool
version: git
summary: command line tool for doing basic Jenkins maintenance tasks
description: |
  jentool is a command line tool for doing basic Jenkins maintenance tasks.
base: core22
confinement: strict
source-code: https://github.com/toabctl/jentool
issues: https://github.com/toabctl/jentool/issues
license: Apache-2.0

plugs:
  dot-config-jentool:
    interface: personal-files
    read:
    - $HOME/.config/jentool.ini

parts:
  jentool:
    plugin: python
    source: .

apps:
  jentool:
    command: bin/jentool
    plugs:
      - home
      - network
      - dot-config-jentool
